### ISSUE TITLE
Create KNIMECancelation Service?

### ISSUE THREAD

**Issue by gab1one** [knime-ip/knip-scijava#17]
This service would allow for an easy cancellation of Nodes which are powered by SciJava Plugins.

Requires changes in SciJava, maybe add ops which can be canceled themselves. (Especially interesting for the more complex highlevel ops.

**Comment by Squareys** [comment]
I think there already is something cancellable in Scijava.

**Comment by Squareys** [comment]
Instead of having a service or such, you could simply check for "isCancelled" on the module after every row.

**Comment by gab1one** [comment]
Duplicate of #14
