### ISSUE TITLE
Column selection widget for SciJava Nodes

### ISSUE THREAD

**Issue by gab1one** [knime-ip/knip-scijava#22]
All SciJava Nodes should use be able to use a column selection widget.
This widget allows:
- [x] Selection of columns 
- [ ] ~~Manual entering of values~~
- [ ] Adding values via flow variable
- [x] respect optional parameters, see #21 

see also: https://github.com/knime-ip/knip-scripting/issues/48

**Comment by dietzc** [comment]
How can we manually enter a column name? This is not possible.

**Comment by gab1one** [comment]
I was thinking about what is now in the #27 issue.

**Comment by dietzc** [comment]
Yes, but this issue is independent from the widget itself. The widget has to exist. The decision weather to use it or not is a different one.

**Comment by gab1one** [comment]
This is developed in the [colSelect branch](https://github.com/knime-ip/knip-scijava/tree/ColSelect)

**Comment by dietzc** [comment]
status on that?

**Comment by Squareys** [comment]
@dietzc This is in #49 now too, right?
