### ISSUE TITLE
Ensure log messages of Commands are entered into the KNIME log.

### ISSUE THREAD

**Issue by gab1one** [knime-ip/knip-scijava#28]
###### Problem:

Some log and error messages of Commands are only visible in the dbg stdout, instead of the KNIME log.
The cause seems to be that these Commands log via a `LogService`:

``` java
@Parameter
private LogService log;
```
###### Idea:  KNIMELogService

 Add the `KNIMELogService` with very high priority that pushes the log messages into the KNIME log.

There is already a KNIPLogService in `org.knime.knip.core` it could be refactored and moved to knip-scijava.

**Comment by dietzc** [comment]
absolutely. However, we should add the possibility to the `KNIMELogService`, that KNIME nodes can set their individual `LogLevel` and also somehow add information which node / class published a log message. Basically, we should mimic some of the behaviour of the the `NodeLogger` of KNIME in the `KNIMELogService` while still implementing `LogService`.
