### ISSUE TITLE
Allow mapping one column to several inputs?

### ISSUE THREAD

**Issue by gab1one** [knime-ip/knip-scijava#29]
Currently a column can only be mapped to one input, but there is no reason to not allow a column to be mapped to several inputs. This is  possible in the `Java Snippet` Node.

@dietzc @Squareys what do you think?

**Comment by Squareys** [comment]
@gab1one I think you should be able to map a column to multiple inputs. :)

**Comment by gab1one** [comment]
This is possible with the new column selection widget.
