### ISSUE TITLE
Add Dimension selection Widget

### ISSUE THREAD

**Issue by gab1one** [knime-ip/knip-scijava#32]
This is a feature of many KNIP Nodes and should be available in the SciJava Nodes as well.
- [x] Design (use the widget from KNIP)
- [ ] Specify input type(s) that are supplied by the Widget
- [ ] Alternatively use widget input to modify input images, see mockup:
  <img width="920" alt="screen shot 2016-01-25 at 9 56 34 am" src="https://cloud.githubusercontent.com/assets/1938154/12556132/f83d605c-c349-11e5-9886-39b1176f641a.png">

**Comment by gab1one** [comment]
@dietzc What do you think?

**Comment by dietzc** [comment]
I think it's worth a try. the dim selection will not "pop-up" right? rather it will be visible next to the column selection?!

**Comment by gab1one** [comment]
Yes it can either be there all the time or become visible when you click the the  **Select Dimensions** button.

**Comment by dietzc** [comment]
keep it simple first. functionality is more important at the current stage. we can beautify things later!

**Comment by dietzc** [comment]
this actually is image processing specific. please migrate to knip2.

**Comment by dietzc** [comment]
this is not scijava related. it's knip-imagej2 related.
