### ISSUE TITLE
Abstract Pre / Post-processing to allow extention to other datamodels in the future

### ISSUE THREAD

**Issue by gab1one** [knime-ip/knip-scijava#37]
We will implement support for other data types than BufferedDataTable in the near future, the KNIME specific preprocessing framework, especially the mapping need to be refactored so that they are generic enough that they can be easily extended.

Example for future expansion:
- support for table-like structures which don't use `BufferedDataTables` and `DataValue` and `DataCell` paradigm. One obvious example is the `Map<String,O>` data structure which only performs an in-memory mapping.

**Comment by dietzc** [comment]
will not be possible at all.
