### ISSUE TITLE
Node which loads arbitrary scripts or class files.

### ISSUE THREAD

**Issue by gab1one** [knime-ip/knip-scijava#43]
1.1. Idea: File selection. Script is copied into string storage or whatever. Then Dialog is created.
1.2 Mutate button to go back to file selection if desired.

**Comment by dietzc** [comment]
isn't this rather an `Scripting` issue?

**Comment by gab1one** [comment]
True, I moved it: https://github.com/knime-ip/knip-scripting/issues/76
